version: "3.9"
services:
    mqtt-broker:
        image: eclipse-mosquitto:2
        volumes: 
            - ./mosquitto/:/mosquitto/config/
            - ./mosquitto-data:/mosquitto/data/
        ports:
            - "8883:8883"

    mqtt-demo-client:
        build: ./python-demo-client
